In [101]:
import pandas as pd

In [102]:
df = pd.read_csv("fixed_income.csv")

In [103]:
df.info

<bound method DataFrame.info of       Unnamed: 0                       Financial Instrument  Coupon  Maturity  \
0              0                   SMMSBK CORP CD 82869ADY8   5.450  Jul25'24
1              1                   BRISBK CORP CD 110001AS3   5.300  Jul26'24
2              2                      SYF CORP CD 87164WN95   3.300  Jul29'24
3              3                   FBFCEN CORP CD 319267KV1   5.250  Jul29'24
4              4                      COF CORP CD 14042TJA6   3.350  Aug05'24
...          ...                                        ...     ...       ...
4433        5273   US-T GOVT Note STRIPS Interest 912834RQ3   0.000  Jul31'24
4434        5274  US-T GOVT Note STRIPS Principal 9128207S0   0.000  Jul31'24
4435        5275                   US-T GOVT Note 9128282N9   2.125  Jul31'24
4436        5276                   US-T GOVT Bill 912797KR7   0.000  Jul30'24
4437        5277                   US-T GOVT Bill 912797JT5   0.000  Jul25'24

          Ratings Issuer Debt/Equity  Issue Date  Time-To-Maturity (TTM)  \
0               0                  0  Oct 25 '23                    0.01
1               0                  0  Jul 28 '23                    0.01
2               0                  0  Jul 29 '22                    0.02
3               0                  0  Jun 29 '23                    0.02
4               0                  0  Aug 03 '22                    0.04
...           ...                ...         ...                     ...
4433            0                  0  Jul 31 '17                    0.02
4434            0                  0  Jul 31 '17                    0.02
4435  AAA (MOODY)                  0  Jul 31 '17                    0.02
4436            0                  0  Apr 02 '24                    0.02
4437            0                  0  Jan 25 '24                    0.01

     Payment Frequency        Ask  Ask Yield          Duration %    \
0              Monthly  100.00500     3.5110  0.005479452200233936
1              Monthly   99.99800     5.6450  0.008219177834689617
2          Semi-Annual   99.96700     5.6280  0.016438355669379234
3          Semi-Annual   99.99500     5.5960  0.016438355669379234
4          Semi-Annual   99.92100     5.6890    0.5218930244445801
...                ...        ...        ...                   ...
4433                 0   99.89500     5.4820                     0
4434                 0   99.90300     5.0730                     0
4435       Semi-Annual   99.94531     4.9210   0.02190280705690384
4436                 0   99.91320     5.2125                     0
4437                 0   99.98550     5.2930                     0

                  Convexity       Bid  Unnamed: 13          Instrument Type
0                 0.0000003    99.851          0.0  Certificates of Deposit
1                0.00000068    99.850          0.0  Certificates of Deposit
2                 0.0000027    99.813          0.0  Certificates of Deposit
3                 0.0000027    99.846          0.0  Certificates of Deposit
4     0.0027642634231597185    99.881          0.0  Certificates of Deposit
...                     ...       ...          ...                      ...
4433                      0  99.89499          0.0               Treasuries
4434                      0    99.893          0.0               Treasuries
4435              0.0000048    99.933          0.0               Treasuries
4436                      0    99.913          0.0               Treasuries
4437                      0  99.98539          0.0               Treasuries

[4438 rows x 16 columns]>

In [104]:
df.shape

(4438, 16)

In [105]:
df.columns

Index(['Unnamed: 0', 'Financial Instrument', 'Coupon', 'Maturity', 'Ratings',
       'Issuer Debt/Equity', 'Issue Date', 'Time-To-Maturity (TTM)',
       'Payment Frequency', 'Ask', 'Ask Yield', 'Duration %  ', 'Convexity',
       'Bid', 'Unnamed: 13', 'Instrument Type'],
      dtype='object')

In [106]:
df.columns = (
    df.columns
        .str.lower()
        .str.strip()
        .str.replace(":", "", regex = False)
        .str.replace(" ", "_", regex = False)
        .str.replace("/", "_and_", regex = False)
        .str.replace("-", "_", regex = False)
        .str.replace("(", "", regex = False)
        .str.replace(")", "", regex = False)
        .str.replace("%", "pct", regex = False)
)

In [107]:
df.columns

Index(['unnamed_0', 'financial_instrument', 'coupon', 'maturity', 'ratings',
       'issuer_debt_and_equity', 'issue_date', 'time_to_maturity_ttm',
       'payment_frequency', 'ask', 'ask_yield', 'duration_pct', 'convexity',
       'bid', 'unnamed_13', 'instrument_type'],
      dtype='object')

In [108]:
df.dtypes

unnamed_0                   int64
financial_instrument       object
coupon                    float64
maturity                   object
ratings                    object
issuer_debt_and_equity     object
issue_date                 object
time_to_maturity_ttm      float64
payment_frequency          object
ask                       float64
ask_yield                 float64
duration_pct               object
convexity                  object
bid                        object
unnamed_13                float64
instrument_type            object
dtype: object

In [109]:
df["maturity"] = pd.to_datetime(df["maturity"])

C:\Users\aleks\AppData\Local\Temp\ipykernel_26492\277053947.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["maturity"] = pd.to_datetime(df["maturity"])

In [110]:
df["issue_date"] = pd.to_datetime(df["issue_date"])

C:\Users\aleks\AppData\Local\Temp\ipykernel_26492\976425545.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["issue_date"] = pd.to_datetime(df["issue_date"])

In [111]:
df.dtypes

unnamed_0                          int64
financial_instrument              object
coupon                           float64
maturity                  datetime64[ns]
ratings                           object
issuer_debt_and_equity            object
issue_date                datetime64[ns]
time_to_maturity_ttm             float64
payment_frequency                 object
ask                              float64
ask_yield                        float64
duration_pct                      object
convexity                         object
bid                               object
unnamed_13                       float64
instrument_type                   object
dtype: object

In [112]:
object_columns = df.select_dtypes(include = "object").columns

In [113]:
object_columns

Index(['financial_instrument', 'ratings', 'issuer_debt_and_equity',
       'payment_frequency', 'duration_pct', 'convexity', 'bid',
       'instrument_type'],
      dtype='object')

In [114]:
df[object_columns]

,financial_instrument,ratings,issuer_debt_and_equity,payment_frequency,duration_pct,convexity,bid,instrument_type
0,SMMSBK CORP CD 82869ADY8,0,0,Monthly,0.005479452200233936,0.0000003,99.851,Certificates of Deposit
1,BRISBK CORP CD 110001AS3,0,0,Monthly,0.008219177834689617,0.00000068,99.850,Certificates of Deposit
2,SYF CORP CD 87164WN95,0,0,Semi-Annual,0.016438355669379234,0.0000027,99.813,Certificates of Deposit
3,FBFCEN CORP CD 319267KV1,0,0,Semi-Annual,0.016438355669379234,0.0000027,99.846,Certificates of Deposit
4,COF CORP CD 14042TJA6,0,0,Semi-Annual,0.5218930244445801,0.0027642634231597185,99.881,Certificates of Deposit
...,...,...,...,...,...,...,...,...
4433,US-T GOVT Note STRIPS Interest 912834RQ3,0,0,0,0,0,99.89499,Treasuries
4434,US-T GOVT Note STRIPS Principal 9128207S0,0,0,0,0,0,99.893,Treasuries
4435,US-T GOVT Note 9128282N9,AAA (MOODY),0,Semi-Annual,0.02190280705690384,0.0000048,99.933,Treasuries
4436,US-T GOVT Bill 912797KR7,0,0,0,0,0,99.913,Treasuries
4437,US-T GOVT Bill 912797JT5,0,0,0,0,0,99.98539,Treasuries

In [115]:
num_cols = df.select_dtypes(include = "number").columns

In [116]:
num_cols

Index(['unnamed_0', 'coupon', 'time_to_maturity_ttm', 'ask', 'ask_yield',
       'unnamed_13'],
      dtype='object')

In [117]:
df[num_cols]

,unnamed_0,coupon,time_to_maturity_ttm,ask,ask_yield,unnamed_13
0,0,5.450,0.01,100.00500,3.5110,0.0
1,1,5.300,0.01,99.99800,5.6450,0.0
2,2,3.300,0.02,99.96700,5.6280,0.0
3,3,5.250,0.02,99.99500,5.5960,0.0
4,4,3.350,0.04,99.92100,5.6890,0.0
...,...,...,...,...,...,...
4433,5273,0.000,0.02,99.89500,5.4820,0.0
4434,5274,0.000,0.02,99.90300,5.0730,0.0
4435,5275,2.125,0.02,99.94531,4.9210,0.0
4436,5276,0.000,0.02,99.91320,5.2125,0.0
4437,5277,0.000,0.01,99.98550,5.2930,0.0

In [118]:
df_raw = df.copy()

In [119]:
df.isna().sum()

unnamed_0                 0
financial_instrument      0
coupon                    0
maturity                  0
ratings                   0
issuer_debt_and_equity    0
issue_date                0
time_to_maturity_ttm      0
payment_frequency         0
ask                       0
ask_yield                 0
duration_pct              0
convexity                 0
bid                       0
unnamed_13                0
instrument_type           0
dtype: int64

In [120]:
cols_to_numeric = ["duration_pct", "convexity", "bid"]

for col in cols_to_numeric:
    df[col] = pd.to_numeric(df[col], errors = "coerce")

In [121]:
df[cols_to_numeric].dtypes

duration_pct    float64
convexity       float64
bid             float64
dtype: object

In [122]:
df.isna().sum().sort_values(ascending = False)

duration_pct              308
convexity                 308
bid                       136
unnamed_0                   0
financial_instrument        0
coupon                      0
maturity                    0
ratings                     0
issuer_debt_and_equity      0
issue_date                  0
time_to_maturity_ttm        0
payment_frequency           0
ask                         0
ask_yield                   0
unnamed_13                  0
instrument_type             0
dtype: int64

In [126]:
col = "bid"

bad_mask = df[col].isna() & df_raw[col].notna()

df_raw.loc[bad_mask, col].value_counts()

bid
NoMD    136
Name: count, dtype: int64